#running shel script
name: run-script
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: | 
            env
            # make file runnable, might not be necessary
             chmod +x "${Migrate-repo}/.github/migrate.sh"
              # run script
             "${Migrate-repo}/.github/migrate.sh"
        shell: bash
