#running shel script
name: run-script
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: | 
            
            # make file runnable, might not be necessary
             chmod +x "${GITHUB_WORKSPACE}/Migrate-repo/migrate.sh"
              # run script
             "${GITHUB_WORKSPACE}/Migrate-repo/migrate.sh"
        shell: bash
