#running shel script
name: run-script
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: migrate.sh
        shell: bash
